# Generated by Django 5.0.6 on 2024-06-15 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='user_name',
        ),
    ]
