# Generated by Django 5.0.6 on 2024-06-16 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Email',
            new_name='P_Email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Name',
            new_name='P_Name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Password',
            new_name='P_Password',
        ),
    ]
