# Generated by Django 5.0.6 on 2024-07-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_registration_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catogory', models.CharField(choices=[('1', 'Events'), ('2', 'Campus News'), ('3', 'Notice')], max_length=20)),
                ('description', models.TextField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='registration_form',
            name='student_date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
