# Generated by Django 5.0.6 on 2024-07-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_notice_alter_registration_form_student_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Phd', 'Phd')], default='Bachelor', max_length=20)),
                ('title', models.TextField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='notice',
            name='catogory',
        ),
        migrations.AddField(
            model_name='notice',
            name='category',
            field=models.CharField(choices=[('Events', 'Events'), ('Campus-News', 'Campus News'), ('Notice', 'Notice')], default='Events', max_length=20),
        ),
    ]
