# Generated by Django 5.0.6 on 2024-07-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_programs_remove_notice_catogory_notice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
