# Generated by Django 5.0.6 on 2024-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_profile_p_blood_group_alter_profile_p_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('feedback', models.TextField(max_length=200)),
                ('given_star', models.IntegerField(default=0)),
                ('pic', models.ImageField(default='', upload_to='user_test_img')),
            ],
        ),
    ]
