# Generated by Django 5.0.6 on 2024-07-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='given_star',
            field=models.IntegerField(default=1),
        ),
    ]
