# Generated by Django 5.0.6 on 2024-07-06 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_testimonials_stars_alter_testimonials_given_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='P_Image',
            field=models.ImageField(default='demo.jpg', upload_to='Profile_image/'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='pic',
            field=models.ImageField(default='', upload_to='Profile_image/'),
        ),
    ]
