# Generated by Django 5.0.6 on 2024-07-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_profile_p_image_alter_testimonials_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='P_Image',
            field=models.ImageField(default='Profile_image/demo.jpg', upload_to='Profile_image/ '),
        ),
    ]
