# Generated by Django 5.0.6 on 2024-07-06 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_profile_p_blood_group_alter_profile_p_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='P_Image',
            field=models.ImageField(blank=True, default='Profile_image/demo.jpg', null=True, upload_to='Profile_image/ '),
        ),
    ]
