# Generated by Django 5.0.6 on 2024-07-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_profile_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='P_Image',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_image/ '),
        ),
    ]
