# Generated by Django 5.0.6 on 2024-07-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_profile_p_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Email', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Email', models.CharField(max_length=50)),
                ('Title_of_image1', models.CharField(max_length=50)),
                ('Result_Image1', models.ImageField(upload_to='profile_image/')),
                ('Title_of_image2', models.CharField(max_length=50)),
                ('Result_Image2', models.ImageField(upload_to='profile_image/')),
                ('Title_of_image3', models.CharField(max_length=50)),
                ('Result_Image3', models.ImageField(upload_to='profile_image/')),
                ('Title_of_image4', models.CharField(max_length=50)),
                ('Result_Image4', models.ImageField(upload_to='profile_image/')),
                ('Title_of_image5', models.CharField(max_length=50)),
                ('Result_Image5', models.ImageField(upload_to='profile_image/')),
                ('Title_of_image6', models.CharField(max_length=50)),
                ('Result_Image6', models.ImageField(upload_to='profile_image/')),
            ],
        ),
    ]
